### ISSUE TITLE
Undecleared Tarragon variables

### ISSUE THREAD

**Issue by scottb5612** [SergioMartin86/bamboo6#22]
When translating Cart3d, I am now getting many messages of the follwoing form

bamboo_superMain.cpp: In member function ‘void OlapClass77::initializeOlapRegion77()’:
bamboo_superMain.cpp:1230:40: error: ‘_BambooLoopWrapperIterator1’ was not declared in this scope
bamboo_superMain.cpp:1251:40: error: ‘_BambooLoopWrapperIterator1’ was not declared in this scope
bamboo_superMain.cpp: In member function ‘void OlapClass77::executeOlapRegion77()’:
bamboo_superMain.cpp:1266:40: error: ‘_BambooLoopWrapperIterator1’ was not declared in this scope

**Comment by SergioMartin86** [comment]
This bug is because I tried to get rid of Opaque variable references which are shortcuts taken in the original bamboo to avoid creating language structures in a correct way. When I try them to be non-opaque (pointing to real variables), ROSE goes berserk and starts pointing to strange variables, just like the ones you saw in this bug. 

 I have reverted the commit where I think this error was introduced. Can you update and check again if it is still failing?

**Comment by scottb5612** [comment]
You have fixed this bug. Good.
