### ISSUE TITLE
MPI data types

### ISSUE THREAD

**Issue by scottb5612** [SergioMartin86/bamboo6#23]
I can't seem to fine your posting or email... So I'm setting up a new 'bug' issue.
Bamboo doesn't correctly translate the example str.c
The code runs, but 
The code is here:
https://www.dropbox.com/s/71106daqwkjv5oy/strb.c?dl=0

I print out the addresses of the committed data types.The types print out as zero
in the bamboo version.
I ran the program as
mpirun -n 1 ./a.out -tarragonP0 2 -w 2

**Comment by SergioMartin86** [comment]
I have been able to reproduce the bug. However, a couple of things to be clarified:

- The fact that the datatype is 0 is not a bug, it think it is because identifiers for datatypes in Bamboo start from 0, with +1 increases. For some reason, MPICH starts from 8c000005 (in my case).

- The bug I am witnessing is that the first element of the struct is passed correctly, but not the others. For example, passing A=6, B=2:

-------------------------------------------------
Testing ORIGINAL str.c...
-------------------------------------------------
Datatype: 8c000005 {0}
The element owned by proc #0 after the left shift operation
A: 6 B: 2.000000  

-------------------------------------------------
Testing BAMBOO bamboo_str.cpp...
-------------------------------------------------
Tarragon 0 running on sorken.ucsd.edu
Worker 0 running on 1
Datatype: 0 {0}
The element owned by proc #0 after the left shift operation
A: 6 B: 0.000000

**Comment by SergioMartin86** [comment]
Ok, I implemented the built-in MPI functions and this started working correctly.
