### ISSUE TITLE
In superMain.c, mg_prolong is not being removed after inlining.

### ISSUE THREAD

**Issue by SergioMartin86** [SergioMartin86/bamboo6#29]
For some reason, it's not being removed.

**Comment by scottb5612** [comment]
Yes, that, and one other farily large routine, mg_restrict
Unless we remove these manually, the compilation will fail.
There are also some other smaller routines that I discovered, but they
don't break the compilation.

**Comment by scottb5612** [comment]
Turns out that there are 30  functions that aren't removed
Many of them are functions that are not declared in a global prototype file called
include/prototype.h

However, 12 of these functions are declared in that file and 1 other in limiters.h

I used some scripts to do heavy lifting, removing comments and function bodies

The functions that aren't removed are here:
https://www.dropbox.com/s/ypoj96fzzf6me2w/unprunedFns.txt?dl=0

Here are the functions that appear in one of the head files mentioned above
https://www.dropbox.com/s/5rw7rdrl6dnsuck/fnsDeclared.txt?dl=0

Not sure what is causing this to happen. At least 1 function is never called,
but others are in fact called.

**Comment by SergioMartin86** [comment]
Right now I am in the middle of revamping the whole inliner/prune mechanism, so I'd advise you to suspend tests until my next notice.

A lot of things will work better once I'm done.

**Comment by scottb5612** [comment]
WIll do.
Also, my analysis was not correct. There are 14 unused functions
mg_prolong
mg_restrict
plus these 12 here:
https://www.dropbox.com/s/xnozfylqb8cghs1/UnPrunedFn.txt?dl=0
All fns are declared in a header, except from the mg functions.

**Comment by SergioMartin86** [comment]
This should be solved now.

**Comment by scottb5612** [comment]
It is.
Thanks!
